#ifndef ARM_PREPARE_SYSCALL_RETURN_FAKESTK
#define ARM_PREPARE_SYSCALL_RETURN_FAKESTK

#define NUM_INSTRS_BEFORE_CACHE     (0)
#define STALKER_CACHE_PTR_PTR       (-((4*NUM_INSTRS_BEFORE_CACHE)+8))

#endif
